volumes:
  portainer_data:

services:

  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    restart: always
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data 
    dns:
      - 192.168.2.15
      - 192.168.2.1
    ports:
      - 8000:8000
      - 9000:9000
      - 9443:9443
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  portainer_agent:
    profiles: [ agent ]
    image: portainer/agent:latest
    container_name: portainer
    restart: always
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    dns:
      - 192.168.2.15
      - 192.168.2.1
    ports:
      - 9001:9001
    logging:
      driver: "json-file"
      options:
        max-size: "10m"